import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/global/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        <main className="p-4">
          {children}
        </main>
      </body>
    </html>
  );
}
